language: go
go:
  - 1.5
  - 1.6
  - 1.7

before_script:
  - go get -u github.com/stephanos/strutil
  - go get -u github.com/mattn/goveralls

install:
  - go get -v -t ./...

script:
  - go build
  - go test -v -covermode=count -coverprofile=profile.cov ./...
  - ~/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
